package com.privacyshield.privacy_shield.service;

import org.apache.pdfbox.pdmodel.*;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.springframework.stereotype.Service;
import java.io.*;

@Service
public class PdfGeneratorService {

    // ========================================
    // Redacted text se naya PDF banao
    // ========================================
    public byte[] generateRedactedPdf(
            String redactedText,
            String originalFileName) throws IOException {

        ByteArrayOutputStream outputStream =
                new ByteArrayOutputStream();

        try (PDDocument document = new PDDocument()) {

            // Redacted text ko lines mein split karo
            String[] lines = redactedText.split("\n");

            // Har 45 lines ke liye ek page
            int linesPerPage = 45;
            int totalPages =
                    (int) Math.ceil(
                            (double) lines.length / linesPerPage);

            // Minimum 1 page
            if (totalPages == 0) totalPages = 1;

            for (int pageNum = 0;
                 pageNum < totalPages; pageNum++) {

                PDPage page = new PDPage(
                        PDRectangle.A4);
                document.addPage(page);

                try (PDPageContentStream content =
                             new PDPageContentStream(
                                     document, page)) {

                    // Font set karo
                    PDType1Font font = new PDType1Font(
                            Standard14Fonts.FontName.HELVETICA);
                    PDType1Font fontBold = new PDType1Font(
                            Standard14Fonts
                                    .FontName.HELVETICA_BOLD);

                    // Header — PrivacyShield watermark
                    content.beginText();
                    content.setFont(fontBold, 8);
                    content.setLeading(12f);
                    content.newLineAtOffset(30, 800);
                    content.showText(
                            "REDACTED BY PRIVACYSHIELD" +
                                    " | DPDPA COMPLIANT" +
                                    " | Original: " + originalFileName);
                    content.endText();

                    // Separator line
                    content.moveTo(30, 795);
                    content.lineTo(565, 795);
                    content.stroke();

                    // Content lines
                    content.beginText();
                    content.setFont(font, 9);
                    content.setLeading(14f);
                    content.newLineAtOffset(30, 775);

                    int startLine = pageNum * linesPerPage;
                    int endLine = Math.min(
                            startLine + linesPerPage,
                            lines.length);

                    for (int i = startLine;
                         i < endLine; i++) {
                        String line = lines[i];

                        // Long lines truncate karo
                        if (line.length() > 90) {
                            line = line.substring(0, 87)
                                    + "...";
                        }

                        // Safe characters only
                        line = line.replaceAll(
                                "[^\\x20-\\x7E]", " ");

                        content.showText(line);
                        content.newLine();
                    }
                    content.endText();

                    // Footer
                    content.beginText();
                    content.setFont(font, 7);
                    content.newLineAtOffset(30, 30);
                    content.showText(
                            "Page " + (pageNum + 1) +
                                    " of " + totalPages +
                                    " | Generated by PrivacyShield" +
                                    " | privacyshield.in");
                    content.endText();
                }
            }

            document.save(outputStream);
        }

        return outputStream.toByteArray();
    }
}
